### PR TITLE
feature: UserListDropdown extensible Area

### LINKED ISSUE #3: Extensible areas: Participant dropdown
## Feature request
As discussed in the BBB world conference, the Idea here is to bring the Participant dropdown to be an extensible area as well.

See target area on image bellow:

image

Following the steps of the whiteboard toolbar extensible area, we have to define what properties are we going to send to the html5 client in order for it to correctly interpret the component that it has to mount, and also, we need to specify what possible components is the extensible area going to support (just like the whiteboard toolbar button and the spinner).

### Components: 
- Button;
- Dropdown (as showed in the image);
- Information (non-interactive menu);

The last one would be some information on the user such as connection status, how many messages they sent in the session, and things like that.

### Properties:
For the base component:
```typescript
interface ParticipantDropdownItem {
  label: string,
  icon: string,
  tooltip: string,
}
```

For the Information:
```typescript
class ParticipantDropdownInformation implements ParticipantDropdownItem {
  label: string,
  icon: string,
  tooltip: string,
  type: string
}
```

For the Button:
```typescript
class ParticipantDropdownButton implements ParticipantDropdownItem{
  label: string,
  icon: string,
  tooltip: string,
  type: string,
  onClick: () => void,
  allowed: boolean,
}
```

For the Dropdown:
```typescript
interface ParticipantDropdownDropdown extends ParticipantDropdownItem{
  label: string,
  icon: string,
  tooltip: string,
  type: string,
  onClick: () => void,
  allowed: boolean,
  itemsList: ParticipantDropdownDropdownItem[]
}
```

Those are just schemes for us to base ourselves on, it can change along the way. Any other suggestions, feel free to comment them out.

### PR DESCRIPTION
**Pull request by GuiLeme**
Introduced new extensible area called `UserListDropdownItem`

Also added new hook to get current loaded user list items.

Reminder: After merging this PR it is necessary to add the correct version of the SDK into the userList sample plugin's `package.json`

Closes #3

### CODE REVIEW

**Review by Tainan404 — CHANGES_REQUESTED** [review]
It's missing a readme.md

**Comment by Tainan404** [comment]
Also theres a folder named in pascal case
image

**Comment by Tainan404** [comment]
Why the initial files are .jsx and not .tsx

**Comment by TiagoJacobs** [comment]
Hello @Tainan404 

Steps to review this PR:

1 - Checkout to this PR:
```sh
./scripts/code-review/checkout-to-pr.sh 9
```

2 - Build SDK and publish it to samples and to bigbluebutton-html5

```sh
rm -rf dist/
./scripts/publish-to-samples.sh
./scripts/publish-to-project-folder.sh ~/bbb28/bigbluebutton/bigbluebutton-html5/
```

3 - Start the plugin 

```sh
cd samples/sample-user-list-dropdown-plugin
npm start
```

3 - Adjust the settings.yml to call `sample-user-list-dropdown-plugin`
```sh
  plugins:
    - name: SampleUserListDropdownPlugin
      url: http://127.0.0.1:8080/static/SampleUserListDropdownPlugin.js
```

4 - Restart bigbluebutton-html5 from source

Enjoy:
image

**Pull request merged**
